# Generated by Django 4.2.7 on 2025-06-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="club",
            field=models.CharField(
                blank=True, help_text="Sports club or team", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="css",
            field=models.CharField(
                blank=True,
                help_text="Critical Swim Speed (e.g., 1:30/100m)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="css_updated",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Used to calculate age automatically", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ftp",
            field=models.IntegerField(
                blank=True, help_text="Functional Threshold Power (watts)", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ftp_updated",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="vma",
            field=models.FloatField(
                blank=True, help_text="Maximal Aerobic Speed (km/h)", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="vma_updated",
            field=models.DateField(blank=True, null=True),
        ),
    ]
