# Generated by Django 4.2.7 on 2025-06-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_management",
            "0003_profile_club_profile_css_profile_css_updated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
