# Generated by Django 4.2.7 on 2025-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0004_profile_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("coach", "Coach"), ("athlete", "Athlete")],
                max_length=10,
            ),
        ),
    ]
