# Generated by Django 4.2.7 on 2025-06-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0002_trainingsession_sport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
