# Generated by Django 4.2.7 on 2025-06-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0003_alter_trainingsession_duration_minutes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingsession",
            options={"ordering": ["date", "start_time"]},
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="time",
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="distance",
            field=models.FloatField(
                blank=True, help_text="Planned distance in km", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="intensity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("recovery", "Recovery"),
                    ("easy", "Easy"),
                    ("moderate", "Moderate"),
                    ("hard", "Hard"),
                    ("very_hard", "Very Hard"),
                ],
                default="moderate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="start_time",
            field=models.TimeField(
                blank=True, help_text="Planned start time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed workout description, instructions, or plan",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("missed", "Missed"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
