# Generated by Django 4.2.7 on 2025-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0005_alter_trainingsession_sport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="sport",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("swimming", "Swimming"),
                    ("cycling", "Cycling"),
                    ("trail", "Trail Running"),
                    ("triathlon", "Triathlon"),
                    ("duathlon", "Duathlon"),
                    ("strength", "Strength"),
                    ("other", "Other"),
                ],
                default="running",
                max_length=20,
            ),
        ),
    ]
