# Generated by Django 4.2.7 on 2025-06-16 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0006_alter_trainingsession_sport"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingRepetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repetition_number",
                    models.PositiveIntegerField(
                        help_text="Order of this repetition in the session (1, 2, 3...)"
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        blank=True, help_text="Distance for this repetition", null=True
                    ),
                ),
                (
                    "distance_unit",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Meters"), ("km", "Kilometers")],
                        default="m",
                        max_length=3,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration for this repetition in seconds",
                        null=True,
                    ),
                ),
                (
                    "intensity_percentage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Intensity as percentage of maximum (e.g., 85 for 85%)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "intensity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recovery", "Recovery"),
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("hard", "Hard"),
                            ("very_hard", "Very Hard"),
                        ],
                        help_text="General intensity level",
                        max_length=20,
                    ),
                ),
                (
                    "rest_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Rest time after this repetition in seconds",
                        null=True,
                    ),
                ),
                (
                    "rest_distance_meters",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Rest distance after this repetition in meters",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Specific notes for this repetition (pace, form cues, etc.)",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repetitions",
                        to="training_sessions.trainingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["repetition_number"],
                "unique_together": {("session", "repetition_number")},
            },
        ),
    ]
