# Generated by Django 4.2.7 on 2025-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0007_trainingrepetition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingrepetition",
            name="distance_unit",
        ),
        migrations.RemoveField(
            model_name="trainingrepetition",
            name="duration_seconds",
        ),
        migrations.RemoveField(
            model_name="trainingrepetition",
            name="intensity_percentage",
        ),
        migrations.RemoveField(
            model_name="trainingrepetition",
            name="rest_distance_meters",
        ),
        migrations.RemoveField(
            model_name="trainingrepetition",
            name="rest_time_seconds",
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration for this repetition in minutes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="rest_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Rest time after this repetition in minutes",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trainingrepetition",
            name="distance",
            field=models.FloatField(
                blank=True, help_text="Distance for this repetition in km", null=True
            ),
        ),
        migrations.AlterField(
            model_name="trainingrepetition",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Specific notes for this repetition"
            ),
        ),
    ]
