# Generated by Django 4.2.7 on 2025-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0008_remove_trainingrepetition_distance_unit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingrepetition",
            options={"ordering": ["block_number", "repetition_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="trainingrepetition",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="block_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Which block this repetition belongs to"
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="block_repeat_count",
            field=models.PositiveIntegerField(
                default=1, help_text="How many times to repeat this entire block"
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="distance_unit",
            field=models.CharField(
                blank=True,
                choices=[("m", "Meters"), ("km", "Kilometers")],
                default="m",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="duration_unit",
            field=models.CharField(
                blank=True,
                choices=[("min", "Minutes"), ("sec", "Seconds")],
                default="min",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="duration_value",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration value (number)", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="rest_distance_unit",
            field=models.CharField(
                blank=True,
                choices=[("m", "Meters"), ("km", "Kilometers")],
                default="m",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="rest_distance_value",
            field=models.FloatField(
                blank=True, help_text="Rest distance value", null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="rest_time_unit",
            field=models.CharField(
                blank=True,
                choices=[("min", "Minutes"), ("sec", "Seconds")],
                default="min",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="rest_time_value",
            field=models.PositiveIntegerField(
                blank=True, help_text="Rest time value (number)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="trainingrepetition",
            name="distance",
            field=models.FloatField(
                blank=True, help_text="Distance for this repetition", null=True
            ),
        ),
        migrations.AlterField(
            model_name="trainingrepetition",
            name="repetition_number",
            field=models.PositiveIntegerField(
                help_text="Order of this repetition within the block (1, 2, 3...)"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingrepetition",
            unique_together={("session", "block_number", "repetition_number")},
        ),
        migrations.RemoveField(
            model_name="trainingrepetition",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="trainingrepetition",
            name="rest_minutes",
        ),
    ]
