# Generated by Django 4.2.7 on 2025-06-16 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0009_alter_trainingrepetition_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrepetition",
            name="intensity_percentage",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Intensity as percentage of maximum (e.g., 85 for 85%)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
