# Generated by Django 4.2.7 on 2025-06-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0010_trainingrepetition_intensity_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingrepetition",
            name="duration_unit",
            field=models.CharField(
                blank=True,
                choices=[("sec", "Seconds"), ("min", "Minutes")],
                default="min",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="trainingrepetition",
            name="rest_time_unit",
            field=models.CharField(
                blank=True,
                choices=[("sec", "Seconds"), ("min", "Minutes")],
                default="min",
                max_length=3,
            ),
        ),
    ]
