# Generated by Django 4.2.7 on 2025-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0011_alter_trainingrepetition_duration_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrepetition",
            name="repetition_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How many times to repeat this individual repetition",
            ),
        ),
    ]
