# Generated by Django 4.2.7 on 2025-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_sessions", "0012_trainingrepetition_repetition_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrepetition",
            name="block_rest_time_unit",
            field=models.CharField(
                blank=True,
                choices=[("sec", "Seconds"), ("min", "Minutes")],
                default="min",
                help_text="Unit for block rest time",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="trainingrepetition",
            name="block_rest_time_value",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Rest time after completing the entire block",
                null=True,
            ),
        ),
    ]
