# Generated by Django 4.2.7 on 2025-06-08 05:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of your custom event", max_length=200
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Additional notes about this event"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#007bff", "Blue"),
                            ("#28a745", "Green"),
                            ("#ffc107", "Yellow"),
                            ("#dc3545", "Red"),
                            ("#6c757d", "Gray"),
                            ("#17a2b8", "Teal"),
                            ("#6f42c1", "Purple"),
                            ("#fd7e14", "Orange"),
                            ("#e83e8c", "Pink"),
                            ("#20c997", "Mint"),
                        ],
                        default="#007bff",
                        help_text="Color to display this event on the calendar",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g., #007bff)",
                                regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                            )
                        ],
                    ),
                ),
                ("start_date", models.DateField(help_text="Start date of the event")),
                ("end_date", models.DateField(help_text="End date of the event")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Event",
                "verbose_name_plural": "Custom Events",
                "ordering": ["start_date", "title"],
            },
        ),
    ]
