# Generated by Django 4.2.7 on 2025-06-07 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("swimming", "Swimming"),
                            ("cycling", "Cycling"),
                            ("trail", "Trail Running"),
                            ("triathlon", "Triathlon"),
                            ("duathlon", "Duathlon"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=200)),
                ("venue", models.CharField(blank=True, max_length=200)),
                (
                    "distance",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 42.2km, Sprint, Half",
                        max_length=50,
                    ),
                ),
                (
                    "goal_time",
                    models.CharField(
                        blank=True, help_text="e.g., 3:30:00", max_length=20
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("finish", "Just Finish"),
                            ("pb", "Personal Best"),
                            ("time", "Specific Time"),
                            ("placement", "Top Placement"),
                            ("qualify", "Qualify for Event"),
                            ("experience", "Experience/Fun"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "athlete"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finish_time",
                    models.CharField(
                        blank=True, help_text="Actual finish time", max_length=20
                    ),
                ),
                (
                    "overall_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "category_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "satisfaction",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Very Disappointed"),
                            (2, "Disappointed"),
                            (3, "Neutral"),
                            (4, "Satisfied"),
                            (5, "Very Satisfied"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "race_report",
                    models.TextField(blank=True, help_text="How did the race go?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "race",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="race_events.race",
                    ),
                ),
            ],
        ),
    ]
