# Generated by Django 4.2.7 on 2025-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="race",
            options={"ordering": ["date", "start_time"]},
        ),
        migrations.RemoveField(
            model_name="race",
            name="name",
        ),
        migrations.RemoveField(
            model_name="race",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="race",
            name="sport_type",
        ),
        migrations.RemoveField(
            model_name="race",
            name="time",
        ),
        migrations.AddField(
            model_name="race",
            name="description",
            field=models.TextField(
                blank=True, help_text="Race details, strategy, or notes"
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="sport",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("swimming", "Swimming"),
                    ("cycling", "Cycling"),
                    ("trail", "Trail Running"),
                    ("triathlon", "Triathlon"),
                    ("duathlon", "Duathlon"),
                    ("other", "Other"),
                ],
                default="running",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="start_time",
            field=models.TimeField(blank=True, help_text="Race start time", null=True),
        ),
        migrations.AddField(
            model_name="race",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("missed", "Missed"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="title",
            field=models.CharField(
                default="Untitled Race",
                help_text="e.g., Paris Marathon 2025",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
